@baseUrl=http://localhost:3000/api/v1

###
GET {{baseUrl}}/accounts HTTP/1.1

###
GET {{baseUrl}}/accounts/1 HTTP/1.1

###
GET {{baseUrl}}/accounts/79990001234?field=phone HTTP/1.1

###
PATCH {{baseUrl}}/accounts/1 HTTP/1.1
Content-Type: application/json

{
    "account": {
        "contacts": []
    }
}

###
GET {{baseUrl}}/qrs HTTP/1.1

###
GET {{baseUrl}}/qrs?accountId= HTTP/1.1

###
GET {{baseUrl}}/qrs?accountId=1 HTTP/1.1

###
GET {{baseUrl}}/qrs/SCBM HTTP/1.1

###
POST {{baseUrl}}/qrs/emit HTTP/1.1
Content-Type: application/json

{
    "count": 4,
    "length": 4
}

###
PATCH {{baseUrl}}/qrs/SCBM HTTP/1.1
Content-Type: application/json

{
    "account": {
        "contacts": [{
            "channel": "phone",
            "address": "79990001234"
        }]
    }
}